# Generated by Django 3.1.4 on 2021-04-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('3', 'O+'), ('4', 'O-')], max_length=2)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('case', models.CharField(choices=[('1', 'Accident'), ('2', 'Delivery'), ('3', 'Anemia'), ('4', 'Dialysis'), ('5', 'Operation'), ('6', 'Others')], max_length=20)),
                ('hospital', models.CharField(choices=[('1', 'BPKIHS'), ('2', 'Vijaypur Hospital')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('address', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('bloodGroup', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('3', 'O+'), ('4', 'O-')], max_length=2)),
            ],
        ),
    ]
