# Generated by Django 3.1.4 on 2021-04-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('organisername', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('address', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('bloodGroup', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('3', 'O+'), ('4', 'O-')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WebApp.bloodvalidator')),
                ('patientName', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('3', 'O+'), ('4', 'O-')], max_length=2)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('case', models.CharField(choices=[('1', 'Accident'), ('2', 'Delivery'), ('3', 'Anemia'), ('4', 'Dialysis'), ('5', 'Operation'), ('6', 'Urgent'), ('7', 'Others')], max_length=20)),
                ('hospital', models.CharField(choices=[('1', 'BPKIHS'), ('2', 'Vijaypur Hospital')], max_length=20)),
                ('requiredDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.register')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.blood')),
            ],
        ),
    ]
