# Generated by Django 3.1.4 on 2021-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('hospital', models.CharField(max_length=25)),
                ('bloodGroup', models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=2)),
                ('address', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('emailId', models.EmailField(max_length=50, unique=True)),
                ('bloodGroup', models.CharField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-')], default=1, max_length=2)),
                ('password', models.CharField(max_length=14)),
            ],
        ),
    ]
