# Generated by Django 3.1.4 on 2021-04-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='requiredDate',
            field=models.DateField(),
        ),
    ]
