# Generated by Django 3.1.4 on 2021-04-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20210412_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='register_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.register'),
        ),
        migrations.AddField(
            model_name='register',
            name='available_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
