# Generated by Django 3.1.4 on 2021-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20210415_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_donated_date',
            field=models.DateField(null=True),
        ),
    ]
