# Generated by Django 3.1.4 on 2021-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_register_last_donated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='no_of_donations',
            field=models.FloatField(default=0),
        ),
    ]
