# Generated by Django 3.1.4 on 2021-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_register_no_of_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='no_of_donations',
            field=models.IntegerField(default=0),
        ),
    ]
