# Generated by Django 3.1.4 on 2021-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_blood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
