# Generated by Django 3.1.4 on 2021-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_auto_20210424_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='last_donated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
