# Generated by Django 3.1.4 on 2021-05-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_auto_20210424_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='bloodGroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='blood',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='blood',
            old_name='requiredDate',
            new_name='required_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organisername',
            new_name='organiser_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='bloodGroup',
            new_name='blood_group',
        ),
    ]
