# Generated by Django 3.1.4 on 2021-05-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_auto_20210513_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='register_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.register'),
            preserve_default=False,
        ),
    ]
