# Generated by Django 3.1.4 on 2021-05-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_auto_20210526_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='register_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.register'),
        ),
    ]
